title: My demo site
email: my-email@example.com
description: My description here
destination: docs
baseurl: ""
url: ""
twitter_username: IvaIlieva
github_username:  IvaIlieva

# Build settings
plugins:
  - jekyll-feed


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
